### ISSUE TITLE
Wie nutzt man das AddOn?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/media_manager_plus#1]
Ich habe es installiert. Dabei verschwindet der Original MediaManager aus der Navigation.
In Plus AddOn kann ich Gruppen anlegen und editieren. Mehr jedoch nicht. Da scheint noch etwas nicht ganz zu funktionieren oder?

**Comment by phoebusryan** [comment]
Das ist schon richtig so und beabsichtigt. Man kann Gruppen erstellen und diese dann im Frontend über die API nutzen. Das Addon nutze ich bereits mehrfach in Liveprojekten aber es ist halt nicht dokumentiert und deshalb auch nicht im Installert. Ich wollte es am Redaxotag vorstellen aber da bin ich ja leider nicht dabei.

**Comment by olien** [comment]
Vielleicht hast du ja Lust ne kleine Anleitung zu schreiben... Nur ein paar Stichworte :-)

**Comment by phoebusryan** [comment]
Mache ich gleich. Kriege eh dauernd Anfragen dazu :)
