### ISSUE TITLE
Effekte nur einmal angeben (oder Kopiermöglichkeit)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/media_manager_plus#8]

**Comment by phoebusryan** [comment]
Kannst du hier noch genauer beschreiben was du meinst?

**Comment by olien** [comment]
Nun. Wenn ich für einen Breakpoint Effekte erstellt haben möchte ich diese ja wahrscheinlich leicht geändert für die anderen Breakpoints nutzen. Da wäre es schön die kopieren zu können...
